# Generated by Django 3.2 on 2024-06-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmation_code',
        ),
    ]
