# Generated by Django 3.2 on 2024-06-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240607_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=64),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
