# Generated by Django 3.2 on 2024-06-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
