# Generated by Django 3.2 on 2024-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(),
        ),
    ]
